import React, { useState } from 'react';
import {
  ShieldAlert,
  AlertTriangle,
  ChevronDown,
  ChevronUp,
  Copy,
  Check,
  Search,
  Code2,
  Sparkles,
  CheckSquare,
  Square,
  RotateCcw,
  ListChecks,
  ArrowRight,
  Download,
} from 'lucide-react';
import { useLanguage } from '../i18n/LanguageContext';
import type { SecurityFlaw, Severity } from '../types/scanner';

interface FlawsListProps {
  flaws: SecurityFlaw[];
  initialScore?: number;
  initialGrade?: string;
  hostname?: string;
}

export const FlawsList: React.FC<FlawsListProps> = ({
  flaws,
  initialScore = 75,
  initialGrade = 'B',
  hostname = 'target.com',
}) => {
  const { t } = useLanguage();
  const [filterSeverity, setFilterSeverity] = useState<string>('ALL');
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedId, setExpandedId] = useState<string | null>(flaws[0]?.id || null);
  const [activeCodeTab, setActiveCodeTab] = useState<Record<string, string>>({});
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  // Fix Simulator State
  const [isSimulatorActive, setIsSimulatorActive] = useState(true);
  const [remediatedIds, setRemediatedIds] = useState<Set<string>>(new Set());
  const [copiedPlan, setCopiedPlan] = useState(false);

  const getSeverityBadgeClass = (severity: Severity) => {
    switch (severity) {
      case 'CRITICAL':
        return 'text-rose-400 bg-rose-950/40 border-rose-800/60';
      case 'HIGH':
        return 'text-orange-400 bg-orange-950/40 border-orange-800/60';
      case 'MEDIUM':
        return 'text-amber-400 bg-amber-950/40 border-amber-800/60';
      case 'LOW':
        return 'text-blue-400 bg-blue-950/40 border-blue-800/60';
      default:
        return 'text-slate-400 bg-slate-900 border-slate-700';
    }
  };

  // Toggle remediation simulation for a flaw
  const toggleRemediate = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setRemediatedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  const simulateSelectAllCriticalAndHigh = () => {
    const ids = flaws
      .filter((f) => f.severity === 'CRITICAL' || f.severity === 'HIGH')
      .map((f) => f.id);
    setRemediatedIds(new Set(ids));
  };

  const simulateSelectAll = () => {
    setRemediatedIds(new Set(flaws.map((f) => f.id)));
  };

  const resetSimulator = () => {
    setRemediatedIds(new Set());
  };

  // Calculate projected score based on remediated flaws
  const calculateProjectedScore = () => {
    if (flaws.length === 0) return 100;
    if (remediatedIds.size === flaws.length) return 100;

    const baseScore = initialScore;
    const totalPenalty = Math.max(0, 100 - baseScore);
    const totalCvss = flaws.reduce((acc, f) => acc + Math.max(f.cvssScore, 1), 0);
    const remediatedCvss = flaws
      .filter((f) => remediatedIds.has(f.id))
      .reduce((acc, f) => acc + Math.max(f.cvssScore, 1), 0);

    const recoveredPenalty = totalCvss > 0 ? (remediatedCvss / totalCvss) * totalPenalty : 0;
    return Math.min(100, Math.round(baseScore + recoveredPenalty));
  };

  const getProjectedGrade = (score: number) => {
    if (score >= 95) return 'A+';
    if (score >= 85) return 'A';
    if (score >= 75) return 'B';
    if (score >= 65) return 'C';
    if (score >= 50) return 'D';
    return 'F';
  };

  const projectedScore = calculateProjectedScore();
  const projectedGrade = getProjectedGrade(projectedScore);
  const scoreDiff = projectedScore - initialScore;

  const copyRemediationPlan = () => {
    const lines = [
      `# Security Remediation Action Plan: ${hostname}`,
      `Generated by WEBSCANNER · ${new Date().toLocaleDateString()}`,
      ``,
      `### Projected Impact:`,
      `- Current Posture: ${initialScore}/100 (Grade: ${initialGrade})`,
      `- Projected Posture: ${projectedScore}/100 (Grade: ${projectedGrade}) [${scoreDiff >= 0 ? `+${scoreDiff}` : scoreDiff} pts]`,
      `- Tasks Selected: ${remediatedIds.size} of ${flaws.length} flaws`,
      ``,
      `### Action Items:`,
    ];

    flaws.forEach((flaw, idx) => {
      const isMarked = remediatedIds.has(flaw.id);
      lines.push(
        `- [${isMarked ? 'x' : ' '}] **[${flaw.severity}] ${flaw.title}** (CVSS: ${flaw.cvssScore.toFixed(1)})`
      );
      lines.push(`  - **Category:** ${flaw.category} ${flaw.owaspCategory ? `(${flaw.owaspCategory})` : ''}`);
      lines.push(`  - **Fix:** ${flaw.remediation}`);
      if (flaw.evidence) {
        lines.push(`  - **Evidence:** \`${flaw.evidence}\``);
      }
      lines.push(``);
    });

    lines.push(`_Exported from WEBSCANNER_`);

    navigator.clipboard.writeText(lines.join('\n'));
    setCopiedPlan(true);
    setTimeout(() => setCopiedPlan(false), 2500);
  };

  const filteredFlaws = flaws.filter((flaw) => {
    if (filterSeverity !== 'ALL' && flaw.severity !== filterSeverity) return false;
    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      return (
        flaw.title.toLowerCase().includes(q) ||
        flaw.description.toLowerCase().includes(q) ||
        (flaw.owaspCategory && flaw.owaspCategory.toLowerCase().includes(q)) ||
        flaw.category.toLowerCase().includes(q)
      );
    }
    return true;
  });

  const handleCopyCode = (flawId: string, code: string) => {
    navigator.clipboard.writeText(code);
    setCopiedKey(flawId);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const severityCounts = {
    ALL: flaws.length,
    CRITICAL: flaws.filter((f) => f.severity === 'CRITICAL').length,
    HIGH: flaws.filter((f) => f.severity === 'HIGH').length,
    MEDIUM: flaws.filter((f) => f.severity === 'MEDIUM').length,
    LOW: flaws.filter((f) => f.severity === 'LOW').length,
  };

  return (
    <div className="w-full space-y-4">
      {/* Interactive Fix Simulator & Projected Score Card */}
      {flaws.length > 0 && (
        <div className="bg-gradient-to-r from-slate-900/90 via-slate-900/80 to-slate-900/90 border border-cyan-800/40 rounded-xl p-4 sm:p-5 shadow-lg relative overflow-hidden">
          <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
            {/* Left: Title & Explanation */}
            <div className="space-y-1">
              <div className="flex items-center gap-2">
                <span className="p-1 rounded bg-cyan-500/20 text-cyan-400">
                  <Sparkles className="w-4 h-4" />
                </span>
                <h3 className="text-sm sm:text-base font-bold text-white font-mono flex items-center gap-2">
                  <span>Interactive Fix Simulator & Score Projection</span>
                  <span className="text-[10px] uppercase font-mono px-2 py-0.5 rounded-full bg-cyan-950 text-cyan-300 border border-cyan-700/60">
                    Live
                  </span>
                </h3>
              </div>
              <p className="text-xs text-slate-400 max-w-xl">
                Check off flaws below to simulate real-time posture recovery. See how resolving vulnerabilities directly raises your overall score and letter grade.
              </p>
            </div>

            {/* Middle: Score Projection comparison */}
            <div className="flex items-center gap-3 bg-slate-950/70 px-4 py-2.5 rounded-xl border border-slate-800 shrink-0">
              {/* Baseline */}
              <div className="text-center">
                <div className="text-[10px] uppercase font-mono text-slate-500">Current</div>
                <div className="text-lg font-bold font-mono text-slate-300 tabular-nums">
                  {initialScore}
                  <span className="text-xs font-normal text-slate-500"> ({initialGrade})</span>
                </div>
              </div>

              <ArrowRight className="w-4 h-4 text-cyan-500 shrink-0" />

              {/* Projected */}
              <div className="text-center">
                <div className="text-[10px] uppercase font-mono text-cyan-400 font-semibold">Projected</div>
                <div className="text-xl font-black font-mono text-emerald-400 tabular-nums">
                  {projectedScore}
                  <span className="text-xs font-bold text-emerald-300"> ({projectedGrade})</span>
                </div>
              </div>

              {/* Delta badge */}
              {scoreDiff > 0 && (
                <div className="ml-1 px-2 py-1 rounded bg-emerald-950/60 border border-emerald-700/60 text-emerald-300 text-xs font-mono font-bold">
                  +{scoreDiff} pts
                </div>
              )}
            </div>
          </div>

          {/* Quick action controls for simulator */}
          <div className="mt-4 pt-3 border-t border-slate-800/80 flex flex-wrap items-center justify-between gap-2.5 text-xs">
            <div className="flex items-center gap-2 text-slate-400 font-mono">
              <ListChecks className="w-3.5 h-3.5 text-cyan-400" />
              <span>
                Remediated in simulation:{' '}
                <strong className="text-cyan-300 font-semibold">{remediatedIds.size}</strong> of {flaws.length}
              </span>
            </div>

            <div className="flex flex-wrap items-center gap-2">
              <button
                type="button"
                onClick={simulateSelectAllCriticalAndHigh}
                className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white border border-slate-700 text-[11px] font-mono transition-colors cursor-pointer"
              >
                + Fix All Critical & High
              </button>

              <button
                type="button"
                onClick={simulateSelectAll}
                className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white border border-slate-700 text-[11px] font-mono transition-colors cursor-pointer"
              >
                + Fix All
              </button>

              {remediatedIds.size > 0 && (
                <button
                  type="button"
                  onClick={resetSimulator}
                  className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-rose-300 border border-slate-700 text-[11px] font-mono transition-colors cursor-pointer flex items-center gap-1"
                >
                  <RotateCcw className="w-3 h-3" />
                  <span>Reset</span>
                </button>
              )}

              <button
                type="button"
                onClick={copyRemediationPlan}
                className="px-3 py-1 rounded bg-cyan-500/20 hover:bg-cyan-500/30 text-cyan-300 border border-cyan-500/40 text-[11px] font-mono font-medium transition-colors cursor-pointer flex items-center gap-1.5"
                title="Copy action checklist to clipboard for Jira, GitHub, or Markdown"
              >
                {copiedPlan ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span className="text-emerald-300">Plan Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    <span>Copy Action Checklist</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Controls Bar */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 bg-slate-900/40 p-3 rounded-xl border border-slate-800">
        {/* Severity Filter Tabs */}
        <div className="flex items-center gap-1 overflow-x-auto pb-1 sm:pb-0">
          {(['ALL', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'] as const).map((sev) => {
            const isActive = filterSeverity === sev;
            const count = severityCounts[sev];
            const label = sev === 'ALL' ? t.allSeverities : sev;
            return (
              <button
                key={sev}
                onClick={() => setFilterSeverity(sev)}
                className={`px-3 py-1.5 rounded-lg text-xs font-mono font-medium transition-all whitespace-nowrap cursor-pointer ${
                  isActive
                    ? 'bg-slate-800 text-white border border-slate-700 shadow-sm'
                    : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800/40'
                }`}
              >
                <span>{label}</span>
                <span className="ml-1.5 text-[11px] opacity-70">({count})</span>
              </button>
            );
          })}
        </div>

        {/* Search */}
        <div className="relative min-w-[220px]">
          <Search className="w-3.5 h-3.5 text-slate-500 absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder={t.filterPlaceholder}
            className="w-full pl-8 pr-3 py-1.5 text-xs bg-slate-950 border border-slate-800 rounded-lg text-white placeholder-slate-500 focus:outline-none focus:border-cyan-500 font-mono"
          />
        </div>
      </div>

      {/* Flaws List */}
      {filteredFlaws.length === 0 ? (
        <div className="text-center py-12 bg-slate-900/30 rounded-xl border border-slate-800/60 p-6">
          <ShieldAlert className="w-8 h-8 text-emerald-500 mx-auto mb-2 opacity-80" />
          <h3 className="text-sm font-semibold text-slate-200">{t.noFlawsFound}</h3>
          <p className="text-xs text-slate-500 mt-1 max-w-sm mx-auto">
            {searchQuery
              ? 'Try adjusting your search criteria.'
              : 'All checks for this category passed without vulnerabilities.'}
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {filteredFlaws.map((flaw) => {
            const isExpanded = expandedId === flaw.id;
            const currentTab =
              activeCodeTab[flaw.id] ||
              (flaw.remediationCode?.nginx
                ? 'nginx'
                : flaw.remediationCode?.apache
                ? 'apache'
                : 'express');
            const isRemediated = remediatedIds.has(flaw.id);

            return (
              <div
                key={flaw.id}
                className={`bg-slate-900/70 border rounded-xl overflow-hidden transition-all duration-200 ${
                  isRemediated
                    ? 'border-emerald-700/60 bg-emerald-950/10'
                    : 'border-slate-800 hover:border-slate-700/80'
                }`}
              >
                {/* Header row */}
                <div
                  onClick={() => setExpandedId(isExpanded ? null : flaw.id)}
                  className="w-full p-4 text-left flex items-start sm:items-center justify-between gap-4 cursor-pointer select-none"
                >
                  <div className="flex items-start sm:items-center gap-3 flex-1 min-w-0">
                    {/* Checkbox for simulator */}
                    <button
                      type="button"
                      onClick={(e) => toggleRemediate(flaw.id, e)}
                      className={`mt-0.5 sm:mt-0 p-1 rounded transition-colors cursor-pointer shrink-0 ${
                        isRemediated
                          ? 'text-emerald-400 bg-emerald-950/60 hover:bg-emerald-900/60'
                          : 'text-slate-500 hover:text-slate-300 hover:bg-slate-800'
                      }`}
                      title={isRemediated ? 'Marked as Remediated in simulation' : 'Click to simulate fixing this flaw'}
                    >
                      {isRemediated ? (
                        <CheckSquare className="w-4 h-4 text-emerald-400" />
                      ) : (
                        <Square className="w-4 h-4" />
                      )}
                    </button>

                    <div className="space-y-1.5 flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span
                          className={`text-[11px] font-mono font-bold px-2 py-0.5 rounded border ${getSeverityBadgeClass(
                            flaw.severity
                          )}`}
                        >
                          {flaw.severity}
                        </span>
                        <span className="text-xs font-mono text-slate-400">
                          {t.cvssScoreLabel} {flaw.cvssScore.toFixed(1)}
                        </span>
                        <span aria-hidden="true" className="text-slate-600">
                          ·
                        </span>
                        <span className="text-xs text-slate-400 font-mono truncate">
                          {flaw.category}
                        </span>
                        {flaw.owaspCategory && (
                          <>
                            <span aria-hidden="true" className="text-slate-600 hidden sm:inline">
                              ·
                            </span>
                            <span className="text-xs text-cyan-400/90 font-mono hidden sm:inline">
                              {flaw.owaspCategory}
                            </span>
                          </>
                        )}
                        {isRemediated && (
                          <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-900/40 text-emerald-300 border border-emerald-700/60">
                            ✓ Simulated Fixed
                          </span>
                        )}
                      </div>

                      <h3
                        className={`text-sm sm:text-base font-semibold tracking-tight transition-colors ${
                          isRemediated ? 'text-slate-300 line-through opacity-80' : 'text-slate-100'
                        }`}
                      >
                        {flaw.title}
                      </h3>
                    </div>
                  </div>

                  <div className="text-slate-400 shrink-0 mt-1 sm:mt-0 flex items-center gap-2">
                    {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                  </div>
                </div>

                {/* Expanded Details Body */}
                {isExpanded && (
                  <div className="px-4 pb-4 pt-1 space-y-4 border-t border-slate-800/80 bg-slate-950/40 text-xs sm:text-sm">
                    {/* Description */}
                    <div>
                      <h4 className="text-xs uppercase font-mono font-semibold tracking-wider text-slate-400 mb-1">
                        {t.techVulnerabilityAnalysis}
                      </h4>
                      <p className="text-slate-300 leading-relaxed">{flaw.description}</p>
                    </div>

                    {/* Impact */}
                    <div className="bg-rose-950/20 border border-rose-900/40 p-3 rounded-lg">
                      <h4 className="text-xs uppercase font-mono font-semibold tracking-wider text-rose-300 mb-1 flex items-center gap-1.5">
                        <AlertTriangle className="w-3.5 h-3.5" />
                        <span>{t.exploitationImpact}</span>
                      </h4>
                      <p className="text-rose-200/90 leading-relaxed text-xs">{flaw.impact}</p>
                    </div>

                    {/* Evidence */}
                    {flaw.evidence && (
                      <div>
                        <h4 className="text-xs uppercase font-mono font-semibold tracking-wider text-slate-400 mb-1">
                          {t.evidenceFinding}
                        </h4>
                        <div className="bg-slate-950 p-2.5 rounded-lg border border-slate-800 font-mono text-xs text-amber-300/90 break-all select-all">
                          {flaw.evidence}
                        </div>
                      </div>
                    )}

                    {/* Remediation Guide */}
                    <div>
                      <h4 className="text-xs uppercase font-mono font-semibold tracking-wider text-emerald-400 mb-1">
                        {t.recommendedRemediation}
                      </h4>
                      <p className="text-slate-300 leading-relaxed mb-3">{flaw.remediation}</p>

                      {/* Remediation Code Snippets */}
                      {flaw.remediationCode && Object.keys(flaw.remediationCode).length > 0 && (
                        <div className="rounded-lg border border-slate-800 bg-slate-950 overflow-hidden">
                          <div className="flex items-center justify-between border-b border-slate-800 bg-slate-900/80 px-3 py-1.5">
                            <div className="flex items-center gap-1 text-xs font-mono">
                              <Code2 className="w-3.5 h-3.5 text-cyan-400 mr-1" />
                              {(['nginx', 'apache', 'express', 'cloudflare'] as const).map((k) => {
                                const codeVal = flaw.remediationCode?.[k];
                                if (!codeVal) return null;
                                const isTabActive = currentTab === k;
                                return (
                                  <button
                                    key={k}
                                    onClick={() =>
                                      setActiveCodeTab((prev) => ({ ...prev, [flaw.id]: k }))
                                    }
                                    className={`px-2 py-0.5 rounded text-[11px] uppercase transition-colors cursor-pointer ${
                                      isTabActive
                                        ? 'bg-slate-800 text-cyan-300 font-bold'
                                        : 'text-slate-400 hover:text-slate-200'
                                    }`}
                                  >
                                    {k}
                                  </button>
                                );
                              })}
                            </div>

                            <button
                              onClick={() => {
                                const code =
                                  flaw.remediationCode?.[currentTab as keyof typeof flaw.remediationCode] ||
                                  flaw.remediationCode?.nginx ||
                                  '';
                                handleCopyCode(flaw.id, code);
                              }}
                              className="text-slate-400 hover:text-white flex items-center gap-1 text-[11px] font-mono cursor-pointer transition-colors"
                            >
                              {copiedKey === flaw.id ? (
                                <>
                                  <Check className="w-3 h-3 text-emerald-400" />
                                  <span className="text-emerald-400">{t.copied}</span>
                                </>
                              ) : (
                                <>
                                  <Copy className="w-3 h-3" />
                                  <span>{t.copySnippet}</span>
                                </>
                              )}
                            </button>
                          </div>

                          <pre className="p-3 text-xs font-mono text-cyan-200/90 overflow-x-auto bg-slate-950">
                            <code>
                              {flaw.remediationCode[currentTab as keyof typeof flaw.remediationCode] ||
                                flaw.remediationCode.nginx ||
                                flaw.remediationCode.apache ||
                                flaw.remediationCode.express}
                            </code>
                          </pre>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
